name: mercure-monaisegment
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.10
  - libpng
  - libjpeg-turbo
  - jupyterlab
  - matplotlib
  - pip
  - pip:
    - numpy>=1.24
    - highdicom>=0.23.0
    - typeguard>=2.13.3
    - monai>=1.3.0
    - monai-deploy-app-sdk>=0.7.0
    - nibabel>=4.0.2
    - pydicom>=2.4.0
    - scikit-learn>=1.3.0
    - simpleitk>=2.3.0
    - torch>=2.1.0
    - torchvision>=0.16.0